---
- name: Add signing key for Package Cloud.
  apt_key:
    url: https://packagecloud.io/gpg.key
    state: present

- name: Install Package Cloud repository.
  apt_repository:
    repo: "deb https://packagecloud.io/grafana/stable/debian/ stretch main"
    filename: grafana
    state: present
    update_cache: yes

- name: Install Grafana.
  apt:
    name: grafana
    state: latest

- name: Configure Grafana.
  lineinfile:
    dest: /etc/grafana/grafana.ini
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^; app_mode"
      line: "app_mode = production"
    - regexp: "^; instance_name"
      line: "instance_name = {{ grafana_server_name }}"
    - regexp: "^;protocol"
      line: "protocol = http"
    - regexp: "^;http_port"
      line: "http_port = 3000"
    - regexp: "^;domain"
      line: "domain = {{ grafana_server_name }}"
    - regexp: "^;enforce_domain"
      line: "enforce_domain = false"
    - regexp: "^;root_url"
      line: "root_url = https://{{ grafana_server_name }}"
    - regexp: "^;enable_gzip"
      line: "enable_gzip = true"
    - regexp: "^;cert_file"
      line: "cert_file = {{ grafana_tls_cert_path }}"
    - regexp: "^;cert_key"
      line: "cert_key = {{ grafana_tls_key_path }}"
    - regexp: "^;cookie_secure"
      line: "cookie_secure = true"
    - regexp: "^;check_for_updates"
      line: "check_for_updates = {{ grafana_updates_check }}"
    - regexp: "^;disable_gravatar"
      line: "disable_gravatar = {{ grafana_disable_gravatar }}"
    - regexp: "^;allow_sign_up"
      line: "allow_sign_up = {{ grafana_allow_sign_up }}"
    - regexp: "^;allow_org_create"
      line: "allow_org_create = {{ grafana_allow_org_create }}"
    - regexp: "^;auto_assign_org"
      line: "auto_assign_org = {{ grafana_auto_assign_org }}"
    - regexp: "^;auto_assign_org_role"
      line: "auto_assign_org_role = {{ grafana_auto_assign_org_role }}"
    - regexp: "^;default_theme"
      line: "default_theme = {{ grafana_default_theme }}"
    - regexp: "^;disable_login_form"
      line: "disable_login_form = {{ grafana_disable_login_form }}"
    - regexp: "^;enabled"
      line: "enabled = {{ grafana_anonymous_auth }}"
      insertafter: "^[auth.anonymous]"
    - regexp: "^;org_name"
      line: "org_name = {{ grafana_org_name }}"
      insertafter: "^[auth.anonymous]"
  notify: reload grafana

- name: Enable and start grafana-server.
  service:
    name: grafana-server
    state: restarted
    enabled: yes
