---
- name: Install dnsmasq.                                                          
  apt:                                                                          
    name: dnsmasq                                                     
    state: present

- name: Install dnsmasq configuration
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: "0644"
  tags: dnsmasq-cfg
  notify: restart dnsmasq