---
- include: tor.yml
  tags: tor

- include: privoxy.yml
  tags: privoxy

- include: dnsmasq.yml
  tags: dnsmasq

- include: nginx.yml
  tags: nginx

#- include: iptables.yml
#  tags: iptables

- name: Make sure all of the expected ports are listening.                                 
  wait_for:
    host: "{{ ansible_host | default('localhost') }}"
    port: "{{ item | int }}"
    delay: 3
    state: started
  with_items:
    - 53
    - 5353
    - 3000
    - 8118
    - 9090
    - 9093
    - 9115