---
- name: Install some prerequisites.
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - dirmngr

- name: Add signing key for Tor Project.
  apt_key:
    keyserver: keys.gnupg.net
    id: A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89
    state: present

- name: Install Tor Project apt repository.
  apt_repository:
    repo: "deb https://deb.torproject.org/torproject.org/ stretch main"
    state: present
  register: add_tor_repo

- name: Update apt cache.
  apt:
    update_cache: yes
  when: add_tor_repo.changed

- name: Install Tor.
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - tor
    - deb.torproject.org-keyring

- name: Install Tor configuration.
  template:
    src: torrc.j2
    dest: "/etc/tor/torrc"
    owner: root
    group: root
    mode: "0644"
  tags: tor-cfg
  notify: restart tor