---
- name: restart tor
  service:
    name: tor
    state: restarted
    enabled: yes

- name: restart privoxy
  service:
    name: privoxy
    state: restarted
    enabled: yes

- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted
    enabled: yes

- name: restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes