---
- name: Set up stretch-backports.
  apt_repository:
    repo: 'deb http://http.us.debian.org/debian/ stretch-backports main contrib non-free'
    state: present

- name: Install Prometheus node exporter and mtail.
  apt:
    name: "{{ item }}"
    default_release: stretch-backports
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - prometheus-node-exporter
    - mtail

- name: Install mtail configuration.
  copy:
    src: mtail
    dest: "/etc/default/mtail"
    owner: root
    group: root
    mode: "0644"

- name: Install mtail syslog parsing config.
  copy:
    src: kernel.mtail
    dest: "/etc/mtail/kernel.mtail"
    owner: root
    group: root
    mode: "0644"

- name: Start Prometheus node exporter and mtail.
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - prometheus-node-exporter
    - mtail

- name: Only allow the log server to scrape the metrics.
  ufw:
    rule: allow
    from: "{{ hostvars[groups.logserver.0].ansible_default_ipv4.address }}"
    port: "{{ item }}"
    proto: tcp
  with_items:
    - 9100
    - 3903
